# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - weatherapp-practice

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://weatherappcr.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_7bdbf8f7756a47e285cd2049c0b7c773 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_12af5b9a516447938abe68a08daab040 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: weatherappcr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_7bdbf8f7756a47e285cd2049c0b7c773 }}/weatherapp:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'weatherapp-practice'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_5723ac659dfa4feb989809232f89c5f8 }}
        images: 'weatherappcr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_7bdbf8f7756a47e285cd2049c0b7c773 }}/weatherapp:${{ github.sha }}'